---

image: "reporunner/golang-alpine"
checkout_dir: /go/src/github.com/Luzifer/vault-totp

commands:
  - make ci

environment:
  CGO_ENABLED: 0
  GO111MODULE: on
  MOD_MODE: readonly
  ARCHS: linux/amd64 linux/arm darwin/amd64
